version: "2.1"
services:
  web: 
    build: .
    depends_on: 
     - mysql
    ports:
     - "80:80"
  mysql:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senetic
