<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nelmio_security.csp_reporter_controller' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/Controller/ContentSecurityPolicyController.php';
include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/ContentSecurityPolicy/Violation/Log/Logger.php';
include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/ContentSecurityPolicy/Violation/Log/LogFormatterInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/ContentSecurityPolicy/Violation/Log/LogFormatter.php';
include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/ContentSecurityPolicy/Violation/Filter/Filter.php';
include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/ContentSecurityPolicy/Violation/Filter/NoiseDetectorInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/ContentSecurityPolicy/Violation/Filter/DomainsNoiseDetector.php';
include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/ContentSecurityPolicy/Violation/Filter/DomainsRegexNoiseDetector.php';
include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/ContentSecurityPolicy/Violation/Filter/SchemesNoiseDetector.php';
include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/ContentSecurityPolicy/Violation/Filter/InjectedScriptsNoiseDetector.php';
include_once $this->targetDirs[3].'/vendor/nelmio/security-bundle/ContentSecurityPolicy/Violation/Filter/BrowserBugsNoiseDetector.php';

$a = new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\Filter();
$a->addNoiseDetector(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\DomainsNoiseDetector());
$a->addNoiseDetector(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\DomainsRegexNoiseDetector());
$a->addNoiseDetector(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\SchemesNoiseDetector());
$a->addNoiseDetector(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\InjectedScriptsNoiseDetector());
$a->addNoiseDetector(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Filter\BrowserBugsNoiseDetector(($this->privates['nelmio_security.ua_parser.ua_php.provider'] ?? $this->load('getNelmioSecurity_UaParser_UaPhp_ProviderService.php'))));

return $this->services['nelmio_security.csp_reporter_controller'] = new \Nelmio\SecurityBundle\Controller\ContentSecurityPolicyController(new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Log\Logger(($this->privates['logger'] ?? $this->privates['logger'] = new \Symfony\Component\HttpKernel\Log\Logger()), new \Nelmio\SecurityBundle\ContentSecurityPolicy\Violation\Log\LogFormatter(), 'notice'), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), $a);
