<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_security.ua_parser.ua_php.provider' shared service.

include_once $this->targetDirs[3].'/vendor/ua-parser/uap-php/src/AbstractParser.php';
include_once $this->targetDirs[3].'/vendor/ua-parser/uap-php/src/Parser.php';

return $this->privates['nelmio_security.ua_parser.ua_php.provider'] = \UAParser\Parser::create();
